# 语言
language: node_js
# node版本
node_js:
  - lts/*
# 指定缓存模块
cache:
  directories:
    - node_modules
# 监听分支
branches:
  only:
    - master
# 下载主题
before_install:
  - export TZ='Asia/Shanghai'
  # - git clone https://github.com/shixiaohu2206/hexo-theme-huhu.git themes/huhu
install:
  - npm install hexo-cli -g
  - npm install hexo-deployer-git hexo-generator-feed hexo-renderer-scss hexo-renderer-swig --save
  - npm install
  # - npm install --save shelljs hexo-renderer-webpack hexo-deployer-git hexo-renderer-jade hexo-generator-feed hexo-generator-sitemap hexo-browsersync hexo-generator-archive  hexo-generator-json-content
script:
  - hexo clean
  - hexo generate
after_script:
  - git config user.name "wfanr"
  - git config user.email "wfalloc@163.com"
  - sed -i "s/{GH_TOKEN}/${GH_TOKEN}/g" ./_config.yml
  - sed -i "s/{TC_USER}/${TC_USER}/g" ./_config.yml
  - sed -i "s/{TC_TOKEN}/${TC_TOKEN}/g" ./_config.yml
  - hexo deploy
# 通知
notifications:
  email:
    - wfalloc@163.com
  on_success: change
  on_failure: always