# main menu navigation
menu:
  home: /
  archives: /archives
  about: /about
  rss: /atom.xml

# Miscelaneous
favicon: /favicon.ico

show_post_category: true
show_post_tags: true

active_nav: false # show active status on nav menu

sidebar: true # whether to show the sidebar
widgets:
  # - category
  # - tagcloud
  # - archive
  - recent_posts
  - tag
  - links
links:
  - title: "GitHub"
    url: http://www.github.com/wfalloc
    intro: "GitHub"

# disqus_shortname: wayou

valine_shortname: wfanr
#site statistic
google_analytics:  
# baidu_analytics: 392796d51567e848aebf813b65cb8656
baidu_analytics: 


